### ISSUE TITLE
Manually add cheat cods

### ISSUE THREAD

**Issue by dvt79** [ScriptSK/Reaper-Software-Suite#1]
Hi, in what format and in what folder i must save text code cheat that Multitrainer see my manually saved cheat from ps4trainer site? Try .mc4 and .json but MultiTrainer doesnot see my saved code! Please help!!!
[Metro.txt](https://github.com/ScriptSK/Reaper-Software-Suite/files/7799054/Metro.txt)

**Comment by Pharaoh2k** [comment]
MT2 supports 3 formats: shnext, shn and mc4. It doesn's support JSON format or txt extension.
Use the subdirectories under `%USERPROFILE%\Documents\ReaperReborn\Trainers` to place your trainer and then reload and refresh MT2

**Comment by Pharaoh2k** [comment]
Please note that JSON support has been added in MultiTrainer2 v1.1.8.1
